### ISSUE TITLE
Harvesters congest at mineral deposit

### ISSUE THREAD

**Issue by Morningtea7** [Mirroar/hivemind#60]
Harvester would only mine mineral once until its carry capacity is full. Then the harvester would stuck near the mineral and do nothing. It neither carry minerals back to storage nor put them into a container. The bot would then try to spawn more creeps to mine, but all of them are blocked by the previous harvester.
<img width="348" alt="Snipaste_2022-06-17_23-49-17" src="https://user-images.githubusercontent.com/20536364/174421783-35358930-a3bf-4aaf-bf74-8c7ae3be5ea0.png">

**Comment by Morningtea7** [comment]
`if (target.structureType === STRUCTURE_CONTAINER && distance === 0) {
	// Nothing to do, resources will drop into the container.
}
else {
	creep.transferAny(target);
}`

It seems this if statement is causing the problem which creep would only mine once. Replacing it with `creep.transferAny(target);` solves the issue. Still unsure why the bot keeps spawning new harvesters when there is no place for them to mine.

**Comment by FutureAstroMiner** [comment]
Problem exists in spawn-role/harvester.minerals.ts.

Too many harvesters are being spawned due to a bug in the filter.

https://github.com/Mirroar/hivemind/pull/62 should fix the filter.

**Comment by Mirroar** [comment]
Should be fixed with #62
