### ISSUE TITLE
Raum stirbt, wenn nur ein Terminal und kein Storage vorhanden ist

### ISSUE THREAD

**Issue by Aerics84** [Mirroar/hivemind#70]
Creeps liefern Ressourcen zum Terminal, aber z.B. Builder holen keine Energie aus dem Terminal heraus.
Problem ist, wenn in einem Raum nur ein Terminal und kein Storage vorhanden ist, füllt sich das Terminal immer weiter und z.B. Builder steht keine Energie zur Verfügung und der Raum beginnt zu sterben.

Beispiel: [W54S47](https://screeps.com/a/#!/room/shard1/W54S47)

**Comment by Mirroar** [comment]
This should be fixed by now, logic for builders getting energy has been reworked.
